name: CI - User

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: aartidevops/roboshop-gitops/.github/workflows/ci-reusable.yml@main
    with:
      service_name: user
      acr_name: roboshopdevacr
      language: node
      deploy_uat: true
      deploy_prod: true
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      GITOPS_TOKEN: ${{ secrets.GITOPS_TOKEN }}
